apiVersion: v1
kind: Service
metadata:
  name: tree
  namespace: ecosia
spec:
  type: NodePort
  selector:
    app: tree
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036